### ISSUE TITLE
Leave the keys alone?

### ISSUE THREAD

**Issue by powerjc** [jhampson-dbre/home_assistant#40]
Hi, thank you for taking the time to put this together and keep it up. Very much appreciate the collection and roles. My issue is that I always end up patching your preinstall config role to leave the ssh keys alone. It moves my default controller key and breaks lots of other stuff for me every time I run it. Could we implement a check for an existing key on the target to make this role idempotent, or perhaps a variable to skip the key manipulation altogether, or perhaps just a less common key name to step on less things? 

Happy to put together a PR if one of those sounds acceptable. Thanks again for putting these out there.

**Comment by jhampson-dbre** [comment]
I think it's a good idea to check if key already exists on the controller and adds it to authorized keys on home assistant server. Otherwise if no key exists, then it can still create it like it does now. PR would be welcome 👍

**Comment by jhampson-dbre** [comment]
The fix to use pre-existing keys now available in [v1.1.0](https://github.com/jhampson-dbre/home_assistant/releases/tag/1.1.0) of the collection. I also went ahead and implemented the other suggestions. 
- `preinstall_config_ssh_key_name` - can be used to specify a name for the key file other than `id_rsa`
- `preinstall_config_leave_my_keys_alone` - can be set to `true` to skip all ssh key setup related tasks, so the keys can be fully managed outside the role

Let me know if you run into any problems with the new features!
